---

- name: Add OpenStack repository on Ubuntu Focal (Bobcat)
  become: yes
  become_user: root
  shell: add-apt-repository cloud-archive:bobcat -y


- name: Install NTP
  apt:
    name: chrony
    state: present

- name: Install OpenStack packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-openstackclient

- name: Install SQL database
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - python3-pymysql

- name: Install Message Queue (RabbitMQ)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - rabbitmq-server

- name: Install Memcached
  apt:
    name: memcached
    state: present

- name: Install etcd
  apt:
    name: etcd
    state: present
